//--------------------------------------------------------------------//
// MiniKey data node text source
//   - file path : D:\Rohan\Project\Classic\Source\_tmp\PatchInfo.mmd
//   - time stamp : 2020.08.31 (10:36:37)
//   - exporter : 오재석 (SimplePatchFileGenerator)
//--------------------------------------------------------------------//


str LauncherFileName = "Updater.exe";
str RunFilePath = "RohanPostEffectTester.exe";
str StartPath = "D:\Rohan\Project\Classic\Source\_exe/";

Node "[EXPORT]"
{
	Node "내부"
	{
		str Password = "Qocl!@";
		str RemotePath = "rohan_tmp";
		str URL = "patch.playwith.co.kr";
		str UserName = "rohan";
		bool PassiveMode = false;
		bool Warning = false;
	}
}