//--------------------------------------------------------------------//
// MiniKey data node text source
//   - file path  : D:\FullPack\PatchInfo.mmd
//   - time stamp : 2017.12.26 (13:48:50)
//   - exporter   : pc (SimplePatchFileGenerator)
//--------------------------------------------------------------------//


str LauncherFileName = "none.exe";
str RunFilePath = "tera_setup.exe";
str StartPath = "D:\FullPack\Client/";
bool TryCompress = false;

Node "[EXPORT]"
{
	Node "CDN"
	{
		str Password = "gvkw;hmewi";
		str RemotePath = "main";
		str URL = "111.223.32.241";
		str UserName = "pwhqftp";
		bool Warning = true;
	}
}