//--------------------------------------------------------------------//
// MiniKey data node text source
//   - file path  : d:\Solutions\MiniKey\Tool\MMD Viewer\test.mmd
//   - time stamp : 2018.02.23 (17:04:29)
//   - exporter   : pc (MMD Viewer)
//--------------------------------------------------------------------//


str #_DataTypeTag = "Sample data";
int IQ = 65;
str nameOfHero = "미모와 기품";

Template "T_Position"
{
	int2 pos = (0, 0);
}

Template "T_Rect" : "T_Position"
{
	uint h = 480;
	int2 pos = (10, 20);
	uint w = 640;
}

Template "T_VisibleState"
{
	vec3 bgColor = (0.200, 0.300, 0.400);
	bool focus = false;
	int layer = 128;
	vec3 valueSet = // [3]
		(-1.000, -0.500, -0.500) / (0.000, 0.300, 0.300) / (0.800, -1.000, 0.400);
	bool visible = true;
}

Template "T_WindowBase" : "T_Rect"
{
	uint formID = 0;

	Node "actionMap"
	{
		bar BinaryTest = // [2]
			5B41975D /
			28517129;
		float aniKey = // [4]
			1.000 / 2.500 / 4.600 / 10.000;
		str aniName = // [4]
			"애니0" /
			"애니1" /
			"애니2" /
			"애니3";

		Node "seq" {}
	}

	Node "visibleState" : "T_VisibleState" {}
}

Template "T_MonsterForm"
{
	str EnglishName = "empty";
	str KoreanName = "비었음";
	dint dropMoney = 0;
	duint exp = 0;
	int intelligence = 1;
	uint threeSize = // [3]
		50 / 60 / 70;
}

Node "CharacterWindow" : "T_WindowBase"
{
	uint formID = 21;

	Node "dummy" {}

	Node "visibleState"
	{
		int layer = 256;
		str text = "새 \"비지블\" 스테이트<LF>입니당.";
	}
}

Node "MonsterTable"
{
	Node "Knight" : "T_MonsterForm"
	{
		str EnglishName = "Knight";
		str KoreanName = "얍샵이";
		dint dropMoney = 51234567890;
		duint exp = 301234567890;
		int intelligence = 15;
		uint threeSize = // [3]
			40 / 30 / 40;
	}

	Node "Ogre" : "T_MonsterForm"
	{
		str EnglishName = "Ogre";
		str KoreanName = "오우거";
		duint exp = 201234567890;
		int intelligence = 5;
		uint threeSize = // [3]
			100 / 140 / 120;
	}

	Node "Orc" : "T_MonsterForm"
	{
		str EnglishName = "Orc";
		str KoreanName = "오꾸";
		duint exp = 101234567890;
		int intelligence = 10;
	}

	Node "You" : "T_MonsterForm"
	{
		str EnglishName = "Legend of BABO";
		str KoreanName = "알면서";
		bar You에게만_추가 = FFFF;
		uint threeSize = // [3]
			200 / 220 / 190;
	}
}